package com.scooter.printserver;

import java.util.logging.Logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {



    private static Logger log;

    // config logger
    static {
        String path = App.class.getClassLoader()
                .getResource("com/scooter/printserver/logging.properties")
                .getFile();

        System.setProperty("java.util.logging.config.file", path);

        log = Logger.getLogger(App.class.getName());
    }



    public static void main(String[] args) {

        log.info("-- main method start --");

        SocketServer socketServer = new SocketServer();
        socketServer.start(6666);


    }
}
