/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    private static String TAG = App.class.getName();

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
