/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.scooter.printserver.App;
import com.scooter.printserver.SocketClient;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.*;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Logger;

import static org.junit.Assert.*;

public class AppTest {

    private static Logger logger = Logger.getLogger(AppTest.class.getName());

    SocketClient client1;
    SocketClient client2;



    @Test
    public void givenClient1_whenServerResponds_thenCorrect() {

        client1 = new SocketClient();
        client1.startConnection("127.0.0.1", 6666);

        // get files to send
        File receipt1File = new File(AppTest.class.getClassLoader()
                .getResource("com/scooter/printserver/receipt1.txt")
                .getFile());

        String response = client1.sendFile(receipt1File);
        client1.stopConnection();


        assertEquals("ok", response);

    }




}
