/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.scooter.printserver.App;
import com.scooter.printserver.SocketClient;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.*;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Logger;

import static org.junit.Assert.*;

public class AppTest {

    private static Logger logger = Logger.getLogger(AppTest.class.getName());

    SocketClient client1;
    SocketClient client2;

    @Before
    public void setup() {
        client1 = new SocketClient();
        client1.startConnection("127.0.0.1", 6666);
        client2 = new SocketClient();
        client2.startConnection("127.0.0.1", 6666);
    }

    @After
    public void tearDown() {
        client1.stopConnection();
    }

    @Test
    public void givenClient1_whenServerResponds_thenCorrect() {

        // get files to send
        File receipt1File = new File(AppTest.class.getClassLoader()
                .getResource("com/scooter/printserver/receipt1.txt")
                .getFile());

        client1.sendFile(receipt1File);
    }

    @Test
    public void given2Clients_whenServerResponds_thenCorrect() {

        // get files to send
        File receipt1File = new File(AppTest.class.getClassLoader()
                .getResource("com/scooter/printserver/receipt1.txt")
                .getFile());

        client1.sendFile(receipt1File);

        File receipt2File = new File(AppTest.class.getClassLoader()
                .getResource("com/scooter/printserver/receipt2.txt")
                .getFile());

        client2.sendFile(receipt2File);
    }


}
